@startuml schema
' Style rules
skinparam {
  style StrictUML
  linetype ortho
  padding 2
  RoundCorner 5
}

' Define entities (tables)
entity "Users" as users {
  * id : INTEGER
  --
  * first_name : VARCHAR(250)
  * surname : VARCHAR(250)
  * email : VARCHAR(250)
  role : ENUM user_role
  streak_count : INTEGER
  level : INTEGER
  points : INTEGER
}

entity "Badge" as badge {
  * id : INTEGER
  --
  * name : VARCHAR(100)
  description : VARCHAR(100)
  active_url : VARCHAR(500)
  inactive_url : VARCHAR(500)
}

entity "AwardedBadge" as awarded_badge {
  * user_id : INTEGER
  * badge_id : INTEGER
  --
  awarded_at : TIMESTAMP
}

entity "UserChallenge" as user_challenge {
  * user_id : INTEGER <<FK>>
  * challenge_id : INTEGER <<FK>>
  --
  * status : ENUM challenge_status
}

entity "Challenge" as challenge {
  * id : INTEGER
  --
  * name : VARCHAR(100)
  description: VARCHAR(1000)
  points : INTEGER
  * location_id : INTEGER <<FK>>
}

entity "Location" as location {
  * id : INTEGER
  --
  * geography(Point, 4326)
  name: VARCHAR(100)
  category : ENUM location_type
}

' Define relationships (foreign keys)
users ||--o{ user_challenge
user_challenge }o--|| challenge
challenge }o--|| location
users ||-o{ awarded_badge
awarded_badge }o--|| badge

@enduml