name: Discord Notify

on:
  pull_request:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send rich message
        run: |
          curl -H "Content-Type: application/json" \
          -d "{
            \"content\": \"🔔 New PR opened/updated\n📦 Repo: ${{ github.repository }}\n👤 Author: ${{ github.actor }}\n🔗 PR: ${{ github.event.pull_request.html_url }}\n📝 Title: ${{ github.event.pull_request.title }}\"
          }" \
          ${{ secrets.DISCORD_WEBHOOK }}
